// <auto-generated />
namespace Lib4U.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RunSqlScript : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RunSqlScript));
        
        string IMigrationMetadata.Id
        {
            get { return "202110270308178_RunSqlScript"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
