// <auto-generated />
namespace Lib4U.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterUserIdOnReaders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterUserIdOnReaders));
        
        string IMigrationMetadata.Id
        {
            get { return "202110261744508_AlterUserIdOnReaders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
